---
resources:
- name: github-code
  type: git
  source:
    uri: https://github.com/oldmanyoung/docs-ci.git
    #uri: git@github.com:oldmanyoung/docs-ci.git  # SSH not working from ATG servers
    branch: master
    paths: [project/documentation/*]
    username: ((git-http-user))
    password: ((git-http-token))

jobs:
- name: build-docs
  public: true
  serial: true
  plan:
  - get: github-code
    trigger: false
  - task: run-build-docs
    config:
      platform: linux
      image_resource: 
        type: docker-image
        source: 
#          email: ((docker-hub-email))
#          username: ((docker-hub-username))
#          password: ((docker-hub-password))
          repository: ((docker-hub-base-image))
      inputs:
        - name: github-code
      run:
        path: github-code/build-docs.sh
