---
resources:
- name: github-code-docs
  type: git
  source:
    uri: https://github.com/oldmanyoung/docs-ci.git
    #uri: git@github.com:oldmanyoung/docs-ci.git  # SSH not working from ATG servers
    branch: master
    paths: [project/documentation/*]
- name: github-code-dockerfile
  type: git
  source:
    uri: https://github.com/oldmanyoung/docs-ci.git
    #uri: git@github.com:oldmanyoung/docs-ci.git  # SSH not working from ATG servers
    branch: master
    paths: [Dockerfile]
- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-base-image}}
- name: artf-docker-image
  type: docker-image
  source:
    username: {{artf-username}}
    password: {{artf-password}}
    repository: {{artf-repository-docker}}
#    tag: {{artf-repository-docker-tag}}
    insecure_registries: ["cicd-nginx-artifactory.cisco.com"]

jobs:
- name: build-docs
  public: true
  serial: true
  plan:
  - get: github-code-docs
    trigger: true
  - task: run-build-docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          email: {{docker-hub-email}}
          username: {{docker-hub-username}}
          password: {{docker-hub-password}}
          repository: {{docker-hub-base-image}}
      inputs:
        - name: github-code-docs
      run:
        path: github-code-docs/build-docs.sh
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: github-code-dockerfile
    trigger: true
  - put: docker-image
    params:
      build: github-code-dockerfile
      image_resource:
- name: upload-docker-image-cicd-artifactory
  public: true
  serial: true
  plan:
  - get: github-code-dockerfile
    trigger: true
  - put: artf-docker-image
    params:
      build: github-code-dockerfile
      image_resource:
